# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = /home/miguel/Escritorio/googletest-release-1.8.1/googletest
# Where to find user code.
# USER_DIR = ../samples

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread -std=gnu++11

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = Cliente_unittest Monitor_unittest sendero_unittest ruta_unittest parque_unittest

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

Cliente.o : Cliente.cc Cliente.h estructuras.h

Monitor.o: Monitor.cc Monitor.h estructuras.h

sendero.o: sendero.cc sendero.h


ruta.o: ruta.cc ruta.h Cliente.cc Cliente.h Monitor.cc Monitor.h sendero.cc sendero.h estructuras.h

parque.o: parque.cc parque.h ruta.cc ruta.h Cliente.cc Cliente.h Monitor.cc Monitor.h sendero.cc sendero.h estructuras.h

#

Cliente_unittest.o : Cliente_unittest.cc Cliente.h Cliente.cc

Monitor_unittest.o : Monitor_unittest.cc Monitor.cc Monitor.h

sendero_unittest.o : sendero_unittest.cc sendero.cc sendero.h

ruta_unittest.o : ruta_unittest.cc ruta.cc ruta.h Cliente.cc Cliente.h Monitor.cc Monitor.h sendero.cc sendero.h estructuras.h

parque_unittest.o: parque_unittest.cc parque.cc parque.h ruta.cc ruta.h Cliente.cc Cliente.h Monitor.cc Monitor.h sendero.cc sendero.h estructuras.h



Cliente_unittest : Cliente.o Cliente_unittest.o gtest_main.a
	$(CXX) $(CPPFL AGS) $(CXXFLAGS) $^ -o $@
	
Monitor_unittest : Monitor.o Monitor_unittest.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@

sendero_unittest : sendero.o sendero_unittest.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@

ruta_unittest : ruta.o Cliente.o Monitor.o sendero.o ruta_unittest.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@


parque_unittest : parque.o ruta.o Cliente.o Monitor.o sendero.o parque_unittest.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@